# Generated by Django 5.2.7 on 2025-11-02 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmdb_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        unique=True,
                        verbose_name="TMDb id",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Nom")),
                (
                    "logo_path",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Logo path"
                    ),
                ),
                (
                    "origin_country",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Pays d'origine"
                    ),
                ),
                (
                    "homepage",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Homepage"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="ADMIN",
                        help_text="TMDB or ADMIN",
                        max_length=32,
                        verbose_name="Source",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Production company",
                "verbose_name_plural": "Production companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmdb_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        unique=True,
                        verbose_name="TMDb id",
                    ),
                ),
                ("titre", models.CharField(max_length=512, verbose_name="Titre")),
                (
                    "titre_original",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Titre original"
                    ),
                ),
                (
                    "overview",
                    models.TextField(blank=True, verbose_name="Résumé / overview"),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de sortie"
                    ),
                ),
                (
                    "runtime",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Durée (minutes)"
                    ),
                ),
                (
                    "poster_path",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Poster path"
                    ),
                ),
                (
                    "backdrop_path",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Backdrop path"
                    ),
                ),
                (
                    "vote_average",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Note moyenne TMDb"
                    ),
                ),
                (
                    "vote_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nombre de votes TMDb"
                    ),
                ),
                (
                    "popularity",
                    models.FloatField(blank=True, null=True, verbose_name="Popularité"),
                ),
                (
                    "original_language",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Langue originale"
                    ),
                ),
                (
                    "adult",
                    models.BooleanField(default=False, verbose_name="Film adulte"),
                ),
                (
                    "statut",
                    models.CharField(
                        default="n/a", max_length=64, verbose_name="Statut"
                    ),
                ),
                (
                    "created_via_tmdb",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Importé depuis TMDb"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "production_companies",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="core.productioncompany"
                    ),
                ),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Note",
                    ),
                ),
                ("review", models.TextField(blank=True, verbose_name="Commentaire")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spectateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="core.productioncompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company rating",
                "verbose_name_plural": "Company ratings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spectateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="core.film",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ["-created_at"],
                "unique_together": {("spectateur", "film")},
            },
        ),
        migrations.CreateModel(
            name="FilmRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="Note",
                    ),
                ),
                ("review", models.TextField(blank=True, verbose_name="Commentaire")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="core.film",
                    ),
                ),
                (
                    "spectateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="film_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Film rating",
                "verbose_name_plural": "Film ratings",
                "ordering": ["-created_at"],
                "unique_together": {("spectateur", "film")},
            },
        ),
        migrations.AddIndex(
            model_name="film",
            index=models.Index(fields=["tmdb_id"], name="core_film_tmdb_id_61bd3c_idx"),
        ),
        migrations.AddIndex(
            model_name="film",
            index=models.Index(fields=["statut"], name="core_film_statut_ccf403_idx"),
        ),
        migrations.AddIndex(
            model_name="film",
            index=models.Index(
                fields=["created_via_tmdb"], name="core_film_created_2ae845_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="companyrating",
            unique_together={("spectateur", "company")},
        ),
    ]
